// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../Models/Whisky.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 8016812332812567007),
      name: 'Whisky',
      lastPropertyId: const IdUid(5, 7867108219479427561),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7877939310046406944),
            name: 'objectBoxId',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7931342474079654263),
            name: 'id',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6051815823056951549),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 1562378389083598940),
            name: 'volume',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 7867108219479427561),
            name: 'alcPercent',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 8016812332812567007),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Whisky: EntityDefinition<Whisky>(
        model: _entities[0],
        toOneRelations: (Whisky object) => [],
        toManyRelations: (Whisky object) => {},
        getId: (Whisky object) => object.objectBoxId,
        setId: (Whisky object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (Whisky object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(6);
          fbb.addInt64(0, object.objectBoxId);
          fbb.addInt64(1, object.id);
          fbb.addOffset(2, nameOffset);
          fbb.addInt64(3, object.volume);
          fbb.addInt64(4, object.alcPercent);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Whisky(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0))
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Whisky] entity fields to define ObjectBox queries.
class Whisky_ {
  /// see [Whisky.objectBoxId]
  static final objectBoxId =
      QueryIntegerProperty<Whisky>(_entities[0].properties[0]);

  /// see [Whisky.id]
  static final id = QueryIntegerProperty<Whisky>(_entities[0].properties[1]);

  /// see [Whisky.name]
  static final name = QueryStringProperty<Whisky>(_entities[0].properties[2]);

  /// see [Whisky.volume]
  static final volume =
      QueryIntegerProperty<Whisky>(_entities[0].properties[3]);

  /// see [Whisky.alcPercent]
  static final alcPercent =
      QueryIntegerProperty<Whisky>(_entities[0].properties[4]);
}
